# -*- coding: utf-8 -*-
"""wb_deploy_maas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tsrbr0JzKnPCy0BjJA9PoJ-N2It69XUx

**Hazır modeli yükle**
"""

import pickle
import pandas as pd

# pip install streamlit

import streamlit as st

st.title("Salary Prediction Model: :heavy_dollar_sign:")

model=pickle.load(open('model.pkl','rb'))
tecrube=st.number_input('Tecrube',1,10)
yazili=st.number_input('Sınav',1,10)
mulakat=st.number_input('Mulakat',1,10)
if st.button('Tahmin Et'):
      tahmin=model.predict([[tecrube,yazili,mulakat]])
      tahmin = round(tahmin[0], 2)

      st.write(f"Tahmin Edilen Maas $:(tahmin)")

